function Get-PowerPlatformCheckerFlowChartContext {
    <#
    .SYNOPSIS
        Prepares flow action metadata for recursive graph construction.

    .DESCRIPTION
        Performs the one-time analysis required to build a flowchart graph. It
        assigns stable node IDs, indexes parent-child relationships, detects
        wrapped actions, creates node objects, and resolves all rendered edges.
        The returned context is read-only input for recursive graph assembly.

    .PARAMETER Actions
        Action list generated by Get-PowerPlatformCheckerFlowActionList.

    .OUTPUTS
        System.Management.Automation.PSCustomObject. Returns the indexes, nodes,
        edges, wrapper metadata, and synthetic root used by the graph builder.

    .EXAMPLE
        Prepare action metadata before building the graph.

        PS> $context = Get-PowerPlatformCheckerFlowChartContext -Actions $actions
    #>
    param(
        [Parameter(Mandatory = $true)]
        [object] $Actions
    )

    $actionArray = [System.Collections.Generic.List[object]]::new()
    $switchBranchByName = @{}
    foreach ($sourceAction in @($Actions)) {
        $isSwitchBranchChild = ($sourceAction.PSObject.Properties.Name -contains "ParentAction") -and
            $null -ne $sourceAction.ParentAction -and
            $sourceAction.ParentAction.Type -in @("case", "default")

        if (-not $isSwitchBranchChild) {
            [void]$actionArray.Add($sourceAction)
            continue
        }

        $switchName = [string]$sourceAction.ParentAction.Name
        $branchName = [string]$sourceAction.ParentAction.BranchName
        $branchActionName = "__SwitchBranch__::{0}::{1}::{2}" -f $switchName, $sourceAction.ParentAction.Type, $branchName

        $childAction = $sourceAction.PSObject.Copy()
        $childAction.ParentAction = [pscustomobject]@{ Name = $branchActionName; Type = "actions" }
        [void]$actionArray.Add($childAction)

        if (-not $switchBranchByName.ContainsKey($branchActionName)) {
            $branchAction = [pscustomobject]@{
                Name = $branchActionName
                Type = "SwitchBranch"
                Group = "*"
                RunAfter = @()
                RunAfterStatus = $null
                ParentAction = [pscustomobject]@{ Name = $switchName; Type = "cases" }
                IsTrigger = $false
                DisplayName = $branchName
                BranchLabel = $branchName
            }
            $switchBranchByName[$branchActionName] = $branchAction
            [void]$actionArray.Add($branchAction)
        }
    }

    foreach ($switchAction in @($Actions | Where-Object { $_.Type -eq "Switch" })) {
        foreach ($branch in @($switchAction.SwitchBranches)) {
            $branchActionName = "__SwitchBranch__::{0}::{1}::{2}" -f $switchAction.Name, $branch.Type, $branch.Name
            if ($switchBranchByName.ContainsKey($branchActionName)) { continue }

            $branchAction = [pscustomobject]@{
                Name = $branchActionName
                Type = "SwitchBranch"
                Group = "*"
                RunAfter = @()
                RunAfterStatus = $null
                ParentAction = [pscustomobject]@{ Name = $switchAction.Name; Type = "cases" }
                IsTrigger = $false
                DisplayName = [string]$branch.Name
                BranchLabel = [string]$branch.Name
            }
            $switchBranchByName[$branchActionName] = $branchAction
            [void]$actionArray.Add($branchAction)
        }
    }

    $actionArray = @($actionArray)
    $rootActionName = "__FlowchartRoot__"
    $nodeByName = @{}
    $actionByName = @{}
    $childrenByParent = @{
        $rootActionName = @()
    }
    $hasElseBranchByParent = @{}
    $index = 0

    foreach ($action in $actionArray) {
        if (-not $nodeByName.ContainsKey($action.Name)) {
            $nodeByName[$action.Name] = "action$index"
            $index++
        }
        $actionByName[$action.Name] = $action

        $parentName = $null
        if (($action.PSObject.Properties.Name -contains "ParentAction") -and $null -ne $action.ParentAction) {
            $parentName = $action.ParentAction.Name
        }

        if ([string]::IsNullOrWhiteSpace([string]$parentName)) {
            $childrenByParent[$rootActionName] += $action.Name
            continue
        }

        if (-not $childrenByParent.ContainsKey($parentName)) {
            $childrenByParent[$parentName] = @()
        }
        $childrenByParent[$parentName] += $action.Name

        if ($action.ParentAction.Type -eq "else") {
            $hasElseBranchByParent[$parentName] = $true
        }
    }

    $descendantsByAction = @{}
    foreach ($parentName in $childrenByParent.Keys) {
        $descendants = [System.Collections.Generic.HashSet[string]]::new()
        $pending = [System.Collections.Generic.Queue[string]]::new()
        foreach ($childName in @($childrenByParent[$parentName])) {
            $pending.Enqueue($childName)
        }

        while ($pending.Count -gt 0) {
            $nextName = $pending.Dequeue()
            if (-not $descendants.Add($nextName)) { continue }

            if ($childrenByParent.ContainsKey($nextName)) {
                foreach ($nestedChild in @($childrenByParent[$nextName])) {
                    $pending.Enqueue($nestedChild)
                }
            }
        }

        $descendantsByAction[$parentName] = $descendants
    }

    $wrappedByName = @{}
    foreach ($action in $actionArray) {
        if ($action.IsTrigger -eq $true) { continue }

        $hasChildren = $childrenByParent.ContainsKey($action.Name) -and @($childrenByParent[$action.Name]).Count -gt 0
        $isSwitchBranch = $action.Type -eq "SwitchBranch"
        if (-not $hasChildren -and -not $isSwitchBranch) { continue }

        $descendants = $descendantsByAction[$action.Name]
        $isDecision = $action.Type -in @("If", "Switch")
        # Scope blocks always render as subgraphs regardless of edge topology.
        $isScope = $action.Type -eq "Scope"
        $hasExternalIncoming = $false

        if ($null -ne $action.RunAfter -and $action.RunAfter -ne "") {
            foreach ($sourceName in @($action.RunAfter)) {
                if (-not $descendants.Contains($sourceName)) {
                    $hasExternalIncoming = $true
                    break
                }
            }
        }

        if ($isDecision -or $isSwitchBranch -or $isScope -or $hasExternalIncoming) {
            $wrappedByName[$action.Name] = [pscustomobject]@{
                SubgraphId = "{0}_group" -f $nodeByName[$action.Name]
            }
        }
    }

    $nodes = @()
    $nodeById = @{}
    foreach ($action in $actionArray) {
        $isWrapped = $wrappedByName.ContainsKey($action.Name)
        $isBranchWrapper = $action.Type -in @("If", "Switch")
        if ($isWrapped -and -not $isBranchWrapper) { continue }

        $shape = "Action"
        if ($action.IsTrigger -eq $true) {
            $shape = "Trigger"
        }
        elseif ($action.Type -in @("If", "Switch")) {
            $shape = "Decision"
        }

        $node = [pscustomobject]@{
            Id = $nodeByName[$action.Name]
            Label = if ($action.PSObject.Properties.Name -contains "DisplayName") { [string]$action.DisplayName } else { [string]$action.Name }
            Shape = $shape
        }
        $nodes += $node
        $nodeById[$node.Id] = $node
    }

    $trigger = $actionArray | Where-Object { $_.IsTrigger -eq $true } | Select-Object -First 1
    $edgeKeySet = [System.Collections.Generic.HashSet[string]]::new()
    $edges = [System.Collections.Generic.List[object]]::new()

    foreach ($action in $actionArray | Where-Object { $_.IsTrigger -ne $true }) {
        $toId = $nodeByName[$action.Name]
        $runAfterNames = @()
        if ($null -ne $action.RunAfter -and $action.RunAfter -ne "") {
            $runAfterNames = @($action.RunAfter)
        }

        if ($runAfterNames.Count -gt 0) {
            foreach ($fromName in $runAfterNames) {
                if (-not $nodeByName.ContainsKey($fromName)) { continue }

                $label = ""
                if ($action.PSObject.Properties.Name -contains "RunAfterStatus") {
                    $statuses = @($action.RunAfterStatus.$fromName)
                    if ($statuses.Count -gt 0) {
                        $label = $statuses -join "/"
                    }
                }

                $fromId = Resolve-PowerPlatformCheckerFlowChartFromRenderId -SourceName $fromName -TargetName $action.Name -WrappedByName $wrappedByName -ActionByName $actionByName -NodeByName $nodeByName
                $toId = Resolve-PowerPlatformCheckerFlowChartToRenderId -SourceName $fromName -TargetName $action.Name -WrappedByName $wrappedByName -ActionByName $actionByName -NodeByName $nodeByName
                $edgeKey = "{0}|{1}|{2}" -f $fromId, $label, $toId
                if ($edgeKeySet.Add($edgeKey)) {
                    [void]$edges.Add([pscustomobject]@{
                        From = $fromId
                        To = $toId
                        Label = $label
                    })
                }
            }
            continue
        }

        if ($null -ne $action.ParentAction -and $action.ParentAction.Name) {
            $parentName = $action.ParentAction.Name
            if ($nodeByName.ContainsKey($parentName)) {
                $label = ""
                $isBranchParent = $actionByName.ContainsKey($parentName) -and $actionByName[$parentName].Type -in @("If", "Switch")
                if ($isBranchParent) {
                    if ($actionByName[$parentName].Type -eq "Switch" -and $action.PSObject.Properties.Name -contains "BranchLabel") {
                        $label = [string]$action.BranchLabel
                    }
                    elseif ($action.ParentAction.Type -eq "actions") { $label = "True" }
                    elseif ($action.ParentAction.Type -eq "else") { $label = "False" }
                }

                $fromId = $nodeByName[$parentName]
                if ($wrappedByName.ContainsKey($parentName) -and -not $isBranchParent) { continue }

                if ($wrappedByName.ContainsKey($action.Name)) {
                    $toId = Resolve-PowerPlatformCheckerFlowChartToRenderId -SourceName $parentName -TargetName $action.Name -WrappedByName $wrappedByName -ActionByName $actionByName -NodeByName $nodeByName
                }

                $edgeKey = "{0}|{1}|{2}" -f $fromId, $label, $toId
                if ($edgeKeySet.Add($edgeKey)) {
                    [void]$edges.Add([pscustomobject]@{
                        From = $fromId
                        To = $toId
                        Label = $label
                    })
                }
            }
            continue
        }

        if ($trigger -and $nodeByName.ContainsKey($trigger.Name)) {
            $fromId = $nodeByName[$trigger.Name]
            $toId = Resolve-PowerPlatformCheckerFlowChartToRenderId -SourceName $trigger.Name -TargetName $action.Name -WrappedByName $wrappedByName -ActionByName $actionByName -NodeByName $nodeByName
            $edgeKey = "{0}||{1}" -f $fromId, $toId
            if ($edgeKeySet.Add($edgeKey)) {
                [void]$edges.Add([pscustomobject]@{
                    From = $fromId
                    To = $toId
                    Label = ""
                })
            }
        }
    }

    return [pscustomobject]@{
        IsEmpty = $actionArray.Count -eq 0
        RootActionName = $rootActionName
        WrappedByName = $wrappedByName
        ChildrenByParent = $childrenByParent
        NodeByName = $nodeByName
        HasElseBranchByParent = $hasElseBranchByParent
        ActionByName = $actionByName
        Edges = @($edges | Sort-Object From, Label, To)
        NodeById = $nodeById
    }
}