function Get-PowerPlatformCheckerFlowChart {
    <#
    .SYNOPSIS
        Generates a Mermaid flowchart for a Power Platform flow action list.

    .DESCRIPTION
        Produces markdown that contains a Mermaid flowchart graph, including trigger,
        condition branches, runAfter execution-path labels, and grouped subgraphs for
        scope blocks, continuation-style If branches, and Switch cases/default branches.

    .PARAMETER Actions
        Action list generated by Get-PowerPlatformCheckerFlowActionList.

    .PARAMETER Direction
        Mermaid flow direction. Default Top-to-Bottom (`TB`).

    .PARAMETER OutputFormat
        Output format to return: Mermaid markdown text (default) or graph object.

    .PARAMETER IncludeStyles
        Includes flowchart style metadata in Graph output and Mermaid style
        declarations in text output.

    .PARAMETER StyleOverrides
        Optional style overrides for FlowChart style keys when IncludeStyles is
        set.

    .OUTPUTS
        System.String when OutputFormat is Mermaid. Returns Azure DevOps-flavored Mermaid
        markdown containing a flowchart.

        System.Management.Automation.PSCustomObject when OutputFormat is Graph. Returns a
        recursive FlowchartGraph containing GraphType, Id, ActionName, Title, Direction,
        IsEmpty, Nodes, Edges, and Subgraphs. Each node contains Id, Label, and Shape. Each
        edge contains From, To, and Label. Every item in Subgraphs uses the same FlowchartGraph
        schema and owns the nodes, edges, and nested subgraphs rendered inside that boundary.

    .EXAMPLE
        Build a flowchart markdown block from a parsed flow action list.

        PS> $actions = Get-PowerPlatformCheckerFlowActionList -Path "C:\Flow.json" -Recurse -IncludeTrigger -Properties RunAfter,ParentAction
        PS> Get-PowerPlatformCheckerFlowChart -Actions $actions
    #>

    [CmdletBinding()]
    [OutputType([string], [pscustomobject])]
    param(
        [Parameter(Mandatory = $true, Position = 1)]
        [object] $Actions,

        [Parameter(Mandatory = $false)]
        [ValidateSet("TB", "BT", "LR", "RL")]
        [string] $Direction = "TB",

        [Parameter(Mandatory = $false)]
        [ValidateSet("Mermaid", "Graph")]
        [string] $OutputFormat = "Mermaid",

        [Parameter(Mandatory = $false)]
        [switch] $IncludeStyles,

        [Parameter(Mandatory = $false)]
        [hashtable] $StyleOverrides
    )

    $actionCount = @($Actions).Count
    $actionCountBucket = if ($actionCount -lt 25) { "Small" } elseif ($actionCount -lt 100) { "Medium" } else { "Large" }
    $telemetryProperties = @{
        ActionCountBucket = $actionCountBucket
        Direction = $Direction
        OutputFormat = $OutputFormat
        IncludeStyles = $IncludeStyles.IsPresent
        HasStyleOverrides = $PSBoundParameters.ContainsKey('StyleOverrides')
    }
    Send-THEvent -ModuleName "PowerPlatformChecker" -EventName "Get-PowerPlatformCheckerFlowChart" -PropertiesHash $telemetryProperties

    $graphContext = Get-PowerPlatformCheckerFlowChartContext -Actions $Actions
    $graph = Get-PowerPlatformCheckerFlowChartInternal -GraphContext $graphContext -RootActionName $graphContext.RootActionName -Direction $Direction
    if ($IncludeStyles.IsPresent) {
        $graph = Get-PowerPlatformCheckerFlowChartStyledGraph -Graph $graph -StyleOverrides $StyleOverrides
    }

    return Convert-PowerPlatformCheckerDiagramGraphToOutput -Graph $graph -OutputFormat $OutputFormat
}

