function Get-PowerPlatformCheckerFlowChart {
    <#
    .SYNOPSIS
        Generates a Mermaid flowchart for a Power Platform flow action list.

    .DESCRIPTION
        Produces markdown that contains a Mermaid flowchart graph, including trigger,
        condition branches, and runAfter execution-path labels.

    .PARAMETER Actions
        Action list generated by Get-PowerPlatformCheckerFlowActionList.

    .PARAMETER Direction
        Mermaid flow direction. Default Top-to-Bottom (`TB`).

    .EXAMPLE
        Build a flowchart markdown block from a parsed flow action list.

        PS> $actions = Get-PowerPlatformCheckerFlowActionList -Path "C:\Flow.json" -Recurse -IncludeTrigger -Properties RunAfter,ParentAction
        PS> Get-PowerPlatformCheckerFlowChart -Actions $actions
    #>

    [CmdletBinding()]
    [OutputType([string])]
    param(
        [Parameter(Mandatory = $true, Position = 1)]
        [object] $Actions,

        [Parameter(Mandatory = $false)]
        [ValidateSet("TB", "BT", "LR", "RL")]
        [string] $Direction = "TB"
    )

    $actionCount = @($Actions).Count
    $actionCountBucket = if ($actionCount -lt 25) { "Small" } elseif ($actionCount -lt 100) { "Medium" } else { "Large" }
    $telemetryProperties = @{
        ActionCountBucket = $actionCountBucket
        Direction = $Direction
    }
    Send-THEvent -ModuleName "PowerPlatformChecker" -EventName "Get-PowerPlatformCheckerFlowChart" -PropertiesHash $telemetryProperties

    $newline = [Environment]::NewLine
    $actionArray = @($Actions)
    if ($actionArray.Count -eq 0) {
        # Keep the empty-state snapshot parseable and visible in Mermaid renderers.
        return ":::mermaid$newline flowchart $Direction$newline empty[`"No actions found`"]$newline:::"
    }

    # Build stable node ids once so every edge can reference deterministic ids.
    $nodeByName = @{}
    $index = 0
    foreach ($action in $actionArray) {
        if (-not $nodeByName.ContainsKey($action.Name)) {
            $nodeByName[$action.Name] = "action$index"
            $index++
        }
    }

    # Treat the first trigger as the natural entry point for actions without explicit runAfter/parent links.
    $trigger = $actionArray | Where-Object { $_.IsTrigger -eq $true } | Select-Object -First 1

    $nodeLines = @()
    foreach ($action in $actionArray) {
        $id = $nodeByName[$action.Name]
        $safeName = [string] $action.Name

        # Mermaid syntax uses distinct node shapes for trigger, condition, and standard action nodes.
        if ($action.IsTrigger -eq $true) {
            $nodeLines += "$id([`"$safeName`"] )" -replace " \)",")"
        }
        elseif ($action.Type -eq "If") {
            $nodeLines += "$id{`"$safeName`"}"
        }
        else {
            $nodeLines += "$id[`"$safeName`"]"
        }
    }

    # HashSet prevents duplicate edges in complex branch/parallel patterns.
    $edgeSet = [System.Collections.Generic.HashSet[string]]::new()

    foreach ($action in $actionArray | Where-Object { $_.IsTrigger -ne $true }) {
        $toId = $nodeByName[$action.Name]
        $hasRunAfter = $false

        $runAfterNames = @()
        if ($null -ne $action.RunAfter -and $action.RunAfter -ne "") {
            $runAfterNames = @($action.RunAfter)
            $hasRunAfter = $runAfterNames.Count -gt 0
        }

        # Priority 1: explicit runAfter links with optional status labels.
        if ($hasRunAfter) {
            foreach ($fromName in $runAfterNames) {
                if (-not $nodeByName.ContainsKey($fromName)) { continue }

                $label = ""
                if ($action.PSObject.Properties.Name -contains "RunAfterStatus") {
                    $statuses = @($action.RunAfterStatus.$fromName)
                    if ($statuses.Count -gt 0) {
                        $label = ($statuses -join "/")
                    }
                }

                $fromId = $nodeByName[$fromName]
                $edge = if ($label) { "$fromId -- $label --> $toId" } else { "$fromId --> $toId" }
                $edgeSet.Add($edge) | Out-Null
            }
            continue
        }

        # Priority 2: parent block links (Condition True/False branches).
        if ($null -ne $action.ParentAction -and $action.ParentAction.Name) {
            if ($nodeByName.ContainsKey($action.ParentAction.Name)) {
                $label = ""
                if ($action.ParentAction.Type -eq "actions") { $label = "True" }
                elseif ($action.ParentAction.Type -eq "else") { $label = "False" }

                $fromId = $nodeByName[$action.ParentAction.Name]
                $edge = if ($label) { "$fromId -- $label --> $toId" } else { "$fromId --> $toId" }
                $edgeSet.Add($edge) | Out-Null
            }
            continue
        }

        # Fallback: attach to trigger when no explicit dependency metadata exists.
        if ($trigger -and $nodeByName.ContainsKey($trigger.Name)) {
            $edgeSet.Add("$($nodeByName[$trigger.Name]) --> $toId") | Out-Null
        }
    }

    $markdown = ""
    $markdown += ":::mermaid$newline"
    $markdown += "flowchart $Direction$newline"

    foreach ($nodeLine in ($nodeLines | Select-Object -Unique)) {
        $markdown += "$nodeLine$newline"
    }

    foreach ($edgeLine in $edgeSet) {
        $markdown += "$edgeLine$newline"
    }

    $markdown += ":::"
    return $markdown
}

