on:
  push:
    branches:
      - master
      - main

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Prerequisites
      run: .\build\vsts-prerequisites.ps1
      shell: pwsh
    - name: Validate
      run: .\build\vsts-validate.ps1
      shell: pwsh
    - name: Publish Test Report
      if: always()
      uses: EnricoMi/publish-unit-test-result-action/composite@v2
      with:
        check_name: PowerPlatformChecker Pester Results
        files: TestResults/TEST-*.xml
    - name: Upload Test Artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: testresults-push
        path: TestResults/*
    - name: Build
      run: .\build\vsts-build.ps1 -ApiKey $env:APIKEY
      shell: pwsh
      env:
        APIKEY: ${{ secrets.ApiKey }}
        TENANTID: ${{ secrets.TenantId }}
        APPLICATIONID: ${{ secrets.ApplicationId }}
        CLIENTSECRET: ${{ secrets.ClientSecret }}
        ENVIRONMENTID: ${{ secrets.EnvironmentId }}